# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ee3f3b828d8204d9a0afe4b1374f725fc8e28d227292869904ff120372c2281e04d16a83ca5c291a8af218a2e63e00728eb6d4d56683d052f691591090cb029

test:
  secret_key_base: 219b45cddc140df3444b1decd6788594765c693f316c2962873e4f4fa8a4378fe3a6c98891a7857ec2ffcc124e529e66faf0117b1478b6eab55f6e3ecf43f371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
